name: Creates a tag and release
on:
  workflow_dispatch:

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - run: gh release create $RELEASE --generate-notes --target ${{ github.sha }}
        env:
          RELEASE: v1.0.0
          GH_TOKEN: ${{ github.token }}

