name: Creates a tag and release
on:
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - run: gh release create ${{ github.ref_name }} --generate-notes -t $RELEASE
        env:
          RELEASE: v1.0.0
          GH_TOKEN: ${{ github.token }}

