name: Creates a tag and release
on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: penrosehill/derive-version@v1
        id: version

      - run: gh release create $RELEASE --generate-notes --target ${{ github.sha }}
        env:
          RELEASE: v${{ steps.version.outputs.version }}
          GH_TOKEN: ${{ github.token }}

