name: Creates a tag and release
on:
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - run: gh release create ${GITHUB_REF#refs/*/} --generate-notes -t $RELEASE
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE: v1.0.0

